### PR TITLE
refactor particle class again

### PR DESCRIPTION
**Pull request by fionn**

### CODE REVIEW

**Review by neal-o-r — COMMENTED** [review]
Good stuff, all looks eminently sensible. I think I support the classes we've got here, the logic of inheritance seems pretty clear and useful. 

Couple of questions:

* Position/Momentum: Do we need to keep track of these?

* Factory: I'm not clear on the logic here, is there a reason to keep this in its own class or should we it just live in a helper function? I'm not sure I see the idea behind the ParticleFactory... 

* Flavour: What's the plan there? Are you thinking of storing it in a namedtuple?

**Comment by fionn** [comment]
Re: position and momentum, we absolutely don't. I was thinking that it might be nice if at some point we wanted to use momentum to decide what particles can be produced. Similarly, position can be used to place the particles on the diagram. Let's get rid of both of them, at least for now.

The factory is also mostly unnecessary at this stage. It seemed reasonable that you would want to produce particles without knowing what they are in advance. I still think this might be true, depending on how much of a refactor the `Interaction` class undergoes, so I'll leave it for now mostly as a place for `particle_instances` to live. Feel free to disagree.

`flavour` is an instance of a (non-neutrino) lepton, so we can compose our neutrino with properties of that object. At the moment I'm quite unhappy with this design, but not sure if my sense of aesthetic should guide me here since it seems to work ok.

**Review by neal-o-r — COMMENTED** [review]
We're doing typing! Excellent! 

This all looks good to me, are you happy to merge it to master now, or are there still things you'd like to address?

**Comment by fionn** [comment]
Yay! Yeah, I'm happy to merge I think. You've got to check the "Approve" radio button first. I'll merge then.

**Review by neal-o-r — APPROVED** [review]
Ship it!

**Pull request merged**
